---
variables:
  GO_VERSION: "1.25"
  GO_LINTER_VERSION: "v2.10"
  GOLANG_IMAGE: golang:${GO_VERSION}-alpine
  GOPATH: "$CI_PROJECT_DIR/.go"
  GITLAB_DOCKER_PROXY: gitlab.education.tbank.ru:443/backend-academy-go-2025/lecture-materials/dependency_proxy/containers

cache:
  paths:
    - .go/pkg/mod/

stages:
  - lint
  - test
  - build

lint:
  stage: lint
  image: golangci/golangci-lint:${GO_LINTER_VERSION}-alpine
  script:
    - golangci-lint run -c .golangci.yml --timeout=5m
  rules:
    - when: always

test:
  stage: test
  image: ${GOLANG_IMAGE}
  tags:
    - dind
  services:
    - name: docker:24.0-dind
      alias: docker
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_TLS_VERIFY: 1
    DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
    TESTCONTAINERS_HOST_OVERRIDE: "docker"
    TESTCONTAINERS_RYUK_DISABLED: "true"
  before_script:
    - apk add --no-cache docker-cli
    - echo "$CI_JOB_TOKEN" | docker login gitlab.education.tbank.ru:443 -u gitlab-ci-token --password-stdin

    - docker pull ${GITLAB_DOCKER_PROXY}/postgres:17
    - docker tag ${GITLAB_DOCKER_PROXY}/postgres:17 postgres:17
    
    - docker pull ${GITLAB_DOCKER_PROXY}/postgres:15-alpine
    - docker tag ${GITLAB_DOCKER_PROXY}/postgres:15-alpine postgres:15-alpine
    
    - docker pull ${GITLAB_DOCKER_PROXY}/bitnamilegacy/kafka:4.0.0
    - docker tag ${GITLAB_DOCKER_PROXY}/bitnamilegacy/kafka:4.0.0 bitnamilegacy/kafka:4.0.0
    
    - docker pull ${GITLAB_DOCKER_PROXY}/confluentinc/cp-schema-registry:7.5.0
    - docker tag ${GITLAB_DOCKER_PROXY}/confluentinc/cp-schema-registry:7.5.0 confluentinc/cp-schema-registry:7.5.0
    
    - docker pull ${GITLAB_DOCKER_PROXY}/confluentinc/confluent-local:7.5.0
    - docker tag ${GITLAB_DOCKER_PROXY}/confluentinc/confluent-local:7.5.0 confluentinc/confluent-local:7.5.0

    - docker pull ${GITLAB_DOCKER_PROXY}/valkey/valkey:latest
    - docker tag ${GITLAB_DOCKER_PROXY}/valkey/valkey:latest valkey/valkey:latest
  script:
    - apk add --no-cache gcc musl-dev
    - go test -race -coverprofile=coverage.out ./...
    - go tool cover -func=coverage.out
  coverage: '/total:\s+\(statements\)\s+(\d+.\d+)%/'
  rules:
    - when: always

build:
  stage: build
  image: ${GOLANG_IMAGE}
  script:
    - mkdir -p bin
    - for d in cmd/*; do
      name="$(basename "$d")";
      echo "Building $name";
      go build -o "bin/$name" "./cmd/$name";
      done
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: "$CI_COMMIT_BRANCH =~ /^(master|main)$/"
    - when: never
