FROM golang:1.25-alpine AS build

WORKDIR /src

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /out/bot ./cmd/bot/

FROM alpine:latest

WORKDIR /app

COPY --from=build /out/bot /app
COPY --from=build /src/migrations/bot /app/migrations

EXPOSE 8002

CMD ["/app/bot"]