FROM golang:1.25-alpine AS build

WORKDIR /src

COPY . .

RUN ["go", "build", "-o", "/out/bot", "./cmd/bot/"]

FROM alpine:latest

WORKDIR /app

COPY --from=build /out/bot /app
COPY --from=build /src/migrations/bot /app/migrations

EXPOSE 8002

CMD ["/app/bot"]
