FROM golang:1.25-alpine AS build

WORKDIR /src

COPY . .

RUN ["go", "build", "-o", "/out/scrapper", "./cmd/scrapper/"]

FROM alpine:latest

WORKDIR /app

COPY --from=build /out/scrapper /app
COPY --from=build /src/migrations/scrapper /app/migrations

EXPOSE 8001

CMD ["/app/scrapper"]
