// Code generated by MockGen. DO NOT EDIT.
// Source: scrapper.go
//
// Generated by this command:
//
//	mockgen -source=scrapper.go -destination=mocks_test.go -package=scrapper
//

// Package scrapper is a generated GoMock package.
package scrapper

import (
	context "context"
	reflect "reflect"
	time "time"

	botapi "gitlab.education.tbank.ru/backend-academy-go-2025/homeworks/link-tracker/internal/api/botapi"
	domain "gitlab.education.tbank.ru/backend-academy-go-2025/homeworks/link-tracker/internal/domain"
	githubfetcher "gitlab.education.tbank.ru/backend-academy-go-2025/homeworks/link-tracker/internal/infrastructure/githubfetcher"
	linkstorage "gitlab.education.tbank.ru/backend-academy-go-2025/homeworks/link-tracker/internal/infrastructure/linkstorage"
	stackoverflowfetcher "gitlab.education.tbank.ru/backend-academy-go-2025/homeworks/link-tracker/internal/infrastructure/stackoverflowfetcher"
	gomock "go.uber.org/mock/gomock"
)

// MockLinkStorage is a mock of LinkStorage interface.
type MockLinkStorage struct {
	ctrl     *gomock.Controller
	recorder *MockLinkStorageMockRecorder
	isgomock struct{}
}

// MockLinkStorageMockRecorder is the mock recorder for MockLinkStorage.
type MockLinkStorageMockRecorder struct {
	mock *MockLinkStorage
}

// NewMockLinkStorage creates a new mock instance.
func NewMockLinkStorage(ctrl *gomock.Controller) *MockLinkStorage {
	mock := &MockLinkStorage{ctrl: ctrl}
	mock.recorder = &MockLinkStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLinkStorage) EXPECT() *MockLinkStorageMockRecorder {
	return m.recorder
}

// AddLink mocks base method.
func (m *MockLinkStorage) AddLink(ctx context.Context, chatID int64, request linkstorage.AddLinkInput) (linkstorage.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddLink", ctx, chatID, request)
	ret0, _ := ret[0].(linkstorage.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddLink indicates an expected call of AddLink.
func (mr *MockLinkStorageMockRecorder) AddLink(ctx, chatID, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddLink", reflect.TypeOf((*MockLinkStorage)(nil).AddLink), ctx, chatID, request)
}

// Close mocks base method.
func (m *MockLinkStorage) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockLinkStorageMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockLinkStorage)(nil).Close))
}

// DeleteChat mocks base method.
func (m *MockLinkStorage) DeleteChat(ctx context.Context, chatID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteChat", ctx, chatID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteChat indicates an expected call of DeleteChat.
func (mr *MockLinkStorageMockRecorder) DeleteChat(ctx, chatID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteChat", reflect.TypeOf((*MockLinkStorage)(nil).DeleteChat), ctx, chatID)
}

// DeleteLink mocks base method.
func (m *MockLinkStorage) DeleteLink(ctx context.Context, chatID int64, request linkstorage.DeleteLinkInput) (linkstorage.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLink", ctx, chatID, request)
	ret0, _ := ret[0].(linkstorage.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteLink indicates an expected call of DeleteLink.
func (mr *MockLinkStorageMockRecorder) DeleteLink(ctx, chatID, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLink", reflect.TypeOf((*MockLinkStorage)(nil).DeleteLink), ctx, chatID, request)
}

// GetAllLinks mocks base method.
func (m *MockLinkStorage) GetAllLinks(ctx context.Context) ([]linkstorage.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllLinks", ctx)
	ret0, _ := ret[0].([]linkstorage.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllLinks indicates an expected call of GetAllLinks.
func (mr *MockLinkStorageMockRecorder) GetAllLinks(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllLinks", reflect.TypeOf((*MockLinkStorage)(nil).GetAllLinks), ctx)
}

// GetLastUpdated mocks base method.
func (m *MockLinkStorage) GetLastUpdated(ctx context.Context, linkID int) (time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastUpdated", ctx, linkID)
	ret0, _ := ret[0].(time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastUpdated indicates an expected call of GetLastUpdated.
func (mr *MockLinkStorageMockRecorder) GetLastUpdated(ctx, linkID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastUpdated", reflect.TypeOf((*MockLinkStorage)(nil).GetLastUpdated), ctx, linkID)
}

// GetLinks mocks base method.
func (m *MockLinkStorage) GetLinks(ctx context.Context, chatID int64) ([]linkstorage.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLinks", ctx, chatID)
	ret0, _ := ret[0].([]linkstorage.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLinks indicates an expected call of GetLinks.
func (mr *MockLinkStorageMockRecorder) GetLinks(ctx, chatID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLinks", reflect.TypeOf((*MockLinkStorage)(nil).GetLinks), ctx, chatID)
}

// GetUsersWithLink mocks base method.
func (m *MockLinkStorage) GetUsersWithLink(ctx context.Context, linkID int) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersWithLink", ctx, linkID)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsersWithLink indicates an expected call of GetUsersWithLink.
func (mr *MockLinkStorageMockRecorder) GetUsersWithLink(ctx, linkID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersWithLink", reflect.TypeOf((*MockLinkStorage)(nil).GetUsersWithLink), ctx, linkID)
}

// RegisterChat mocks base method.
func (m *MockLinkStorage) RegisterChat(ctx context.Context, chatID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterChat", ctx, chatID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterChat indicates an expected call of RegisterChat.
func (mr *MockLinkStorageMockRecorder) RegisterChat(ctx, chatID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterChat", reflect.TypeOf((*MockLinkStorage)(nil).RegisterChat), ctx, chatID)
}

// SetLastUpdated mocks base method.
func (m *MockLinkStorage) SetLastUpdated(ctx context.Context, linkID int, lastUpdated time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetLastUpdated", ctx, linkID, lastUpdated)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetLastUpdated indicates an expected call of SetLastUpdated.
func (mr *MockLinkStorageMockRecorder) SetLastUpdated(ctx, linkID, lastUpdated any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLastUpdated", reflect.TypeOf((*MockLinkStorage)(nil).SetLastUpdated), ctx, linkID, lastUpdated)
}

// MockBotClient is a mock of BotClient interface.
type MockBotClient struct {
	ctrl     *gomock.Controller
	recorder *MockBotClientMockRecorder
	isgomock struct{}
}

// MockBotClientMockRecorder is the mock recorder for MockBotClient.
type MockBotClientMockRecorder struct {
	mock *MockBotClient
}

// NewMockBotClient creates a new mock instance.
func NewMockBotClient(ctrl *gomock.Controller) *MockBotClient {
	mock := &MockBotClient{ctrl: ctrl}
	mock.recorder = &MockBotClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBotClient) EXPECT() *MockBotClientMockRecorder {
	return m.recorder
}

// SendUpdate mocks base method.
func (m *MockBotClient) SendUpdate(linkUpdate botapi.LinkUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendUpdate", linkUpdate)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendUpdate indicates an expected call of SendUpdate.
func (mr *MockBotClientMockRecorder) SendUpdate(linkUpdate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendUpdate", reflect.TypeOf((*MockBotClient)(nil).SendUpdate), linkUpdate)
}

// MockgithubFetcher is a mock of githubFetcher interface.
type MockgithubFetcher struct {
	ctrl     *gomock.Controller
	recorder *MockgithubFetcherMockRecorder
	isgomock struct{}
}

// MockgithubFetcherMockRecorder is the mock recorder for MockgithubFetcher.
type MockgithubFetcherMockRecorder struct {
	mock *MockgithubFetcher
}

// NewMockgithubFetcher creates a new mock instance.
func NewMockgithubFetcher(ctrl *gomock.Controller) *MockgithubFetcher {
	mock := &MockgithubFetcher{ctrl: ctrl}
	mock.recorder = &MockgithubFetcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockgithubFetcher) EXPECT() *MockgithubFetcherMockRecorder {
	return m.recorder
}

// FetchUpdates mocks base method.
func (m *MockgithubFetcher) FetchUpdates(repoURL string, since time.Time) ([]githubfetcher.UpdateInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchUpdates", repoURL, since)
	ret0, _ := ret[0].([]githubfetcher.UpdateInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchUpdates indicates an expected call of FetchUpdates.
func (mr *MockgithubFetcherMockRecorder) FetchUpdates(repoURL, since any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchUpdates", reflect.TypeOf((*MockgithubFetcher)(nil).FetchUpdates), repoURL, since)
}

// MockstackoverflowFetcher is a mock of stackoverflowFetcher interface.
type MockstackoverflowFetcher struct {
	ctrl     *gomock.Controller
	recorder *MockstackoverflowFetcherMockRecorder
	isgomock struct{}
}

// MockstackoverflowFetcherMockRecorder is the mock recorder for MockstackoverflowFetcher.
type MockstackoverflowFetcherMockRecorder struct {
	mock *MockstackoverflowFetcher
}

// NewMockstackoverflowFetcher creates a new mock instance.
func NewMockstackoverflowFetcher(ctrl *gomock.Controller) *MockstackoverflowFetcher {
	mock := &MockstackoverflowFetcher{ctrl: ctrl}
	mock.recorder = &MockstackoverflowFetcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockstackoverflowFetcher) EXPECT() *MockstackoverflowFetcherMockRecorder {
	return m.recorder
}

// FetchUpdates mocks base method.
func (m *MockstackoverflowFetcher) FetchUpdates(questionURL string, since time.Time) (*stackoverflowfetcher.QuestionUpdates, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchUpdates", questionURL, since)
	ret0, _ := ret[0].(*stackoverflowfetcher.QuestionUpdates)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchUpdates indicates an expected call of FetchUpdates.
func (mr *MockstackoverflowFetcherMockRecorder) FetchUpdates(questionURL, since any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchUpdates", reflect.TypeOf((*MockstackoverflowFetcher)(nil).FetchUpdates), questionURL, since)
}

// MockLinksCache is a mock of LinksCache interface.
type MockLinksCache struct {
	ctrl     *gomock.Controller
	recorder *MockLinksCacheMockRecorder
	isgomock struct{}
}

// MockLinksCacheMockRecorder is the mock recorder for MockLinksCache.
type MockLinksCacheMockRecorder struct {
	mock *MockLinksCache
}

// NewMockLinksCache creates a new mock instance.
func NewMockLinksCache(ctrl *gomock.Controller) *MockLinksCache {
	mock := &MockLinksCache{ctrl: ctrl}
	mock.recorder = &MockLinksCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLinksCache) EXPECT() *MockLinksCacheMockRecorder {
	return m.recorder
}

// GetLinks mocks base method.
func (m *MockLinksCache) GetLinks(ctx context.Context, chatID int64) ([]domain.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLinks", ctx, chatID)
	ret0, _ := ret[0].([]domain.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLinks indicates an expected call of GetLinks.
func (mr *MockLinksCacheMockRecorder) GetLinks(ctx, chatID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLinks", reflect.TypeOf((*MockLinksCache)(nil).GetLinks), ctx, chatID)
}

// Invalidate mocks base method.
func (m *MockLinksCache) Invalidate(ctx context.Context, chatID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Invalidate", ctx, chatID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Invalidate indicates an expected call of Invalidate.
func (mr *MockLinksCacheMockRecorder) Invalidate(ctx, chatID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Invalidate", reflect.TypeOf((*MockLinksCache)(nil).Invalidate), ctx, chatID)
}

// SetLinks mocks base method.
func (m *MockLinksCache) SetLinks(ctx context.Context, chatID int64, links []domain.Link) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetLinks", ctx, chatID, links)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetLinks indicates an expected call of SetLinks.
func (mr *MockLinksCacheMockRecorder) SetLinks(ctx, chatID, links any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLinks", reflect.TypeOf((*MockLinksCache)(nil).SetLinks), ctx, chatID, links)
}
