// Code generated by MockGen. DO NOT EDIT.
// Source: bot.go
//
// Generated by this command:
//
//	mockgen -source=bot.go -destination=mocks_test.go -package=bot
//

// Package bot is a generated GoMock package.
package bot

import (
	context "context"
	reflect "reflect"

	scrapperapi "gitlab.education.tbank.ru/backend-academy-go-2025/homeworks/link-tracker/internal/api/scrapperapi"
	tgapi "gitlab.education.tbank.ru/backend-academy-go-2025/homeworks/link-tracker/internal/infrastructure/tgapi"
	userstorage "gitlab.education.tbank.ru/backend-academy-go-2025/homeworks/link-tracker/internal/infrastructure/userstorage"
	gomock "go.uber.org/mock/gomock"
)

// MocktelegramAPI is a mock of telegramAPI interface.
type MocktelegramAPI struct {
	ctrl     *gomock.Controller
	recorder *MocktelegramAPIMockRecorder
	isgomock struct{}
}

// MocktelegramAPIMockRecorder is the mock recorder for MocktelegramAPI.
type MocktelegramAPIMockRecorder struct {
	mock *MocktelegramAPI
}

// NewMocktelegramAPI creates a new mock instance.
func NewMocktelegramAPI(ctrl *gomock.Controller) *MocktelegramAPI {
	mock := &MocktelegramAPI{ctrl: ctrl}
	mock.recorder = &MocktelegramAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktelegramAPI) EXPECT() *MocktelegramAPIMockRecorder {
	return m.recorder
}

// GetMessagesChan mocks base method.
func (m *MocktelegramAPI) GetMessagesChan() <-chan tgapi.Update {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessagesChan")
	ret0, _ := ret[0].(<-chan tgapi.Update)
	return ret0
}

// GetMessagesChan indicates an expected call of GetMessagesChan.
func (mr *MocktelegramAPIMockRecorder) GetMessagesChan() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessagesChan", reflect.TypeOf((*MocktelegramAPI)(nil).GetMessagesChan))
}

// SendMessage mocks base method.
func (m *MocktelegramAPI) SendMessage(arg0 int64, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessage", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMessage indicates an expected call of SendMessage.
func (mr *MocktelegramAPIMockRecorder) SendMessage(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessage", reflect.TypeOf((*MocktelegramAPI)(nil).SendMessage), arg0, arg1)
}

// SetupCommands mocks base method.
func (m *MocktelegramAPI) SetupCommands(cmds []tgapi.Commands) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetupCommands", cmds)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetupCommands indicates an expected call of SetupCommands.
func (mr *MocktelegramAPIMockRecorder) SetupCommands(cmds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetupCommands", reflect.TypeOf((*MocktelegramAPI)(nil).SetupCommands), cmds)
}

// MockstoreUserState is a mock of storeUserState interface.
type MockstoreUserState struct {
	ctrl     *gomock.Controller
	recorder *MockstoreUserStateMockRecorder
	isgomock struct{}
}

// MockstoreUserStateMockRecorder is the mock recorder for MockstoreUserState.
type MockstoreUserStateMockRecorder struct {
	mock *MockstoreUserState
}

// NewMockstoreUserState creates a new mock instance.
func NewMockstoreUserState(ctrl *gomock.Controller) *MockstoreUserState {
	mock := &MockstoreUserState{ctrl: ctrl}
	mock.recorder = &MockstoreUserStateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockstoreUserState) EXPECT() *MockstoreUserStateMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockstoreUserState) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockstoreUserStateMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockstoreUserState)(nil).Close))
}

// GetRequest mocks base method.
func (m *MockstoreUserState) GetRequest(ctx context.Context, chatID int64) (userstorage.Request, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRequest", ctx, chatID)
	ret0, _ := ret[0].(userstorage.Request)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRequest indicates an expected call of GetRequest.
func (mr *MockstoreUserStateMockRecorder) GetRequest(ctx, chatID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRequest", reflect.TypeOf((*MockstoreUserState)(nil).GetRequest), ctx, chatID)
}

// GetUserState mocks base method.
func (m *MockstoreUserState) GetUserState(ctx context.Context, chatID int64) (int, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserState", ctx, chatID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetUserState indicates an expected call of GetUserState.
func (mr *MockstoreUserStateMockRecorder) GetUserState(ctx, chatID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserState", reflect.TypeOf((*MockstoreUserState)(nil).GetUserState), ctx, chatID)
}

// SetRequestTags mocks base method.
func (m *MockstoreUserState) SetRequestTags(ctx context.Context, chatID int64, tags []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRequestTags", ctx, chatID, tags)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetRequestTags indicates an expected call of SetRequestTags.
func (mr *MockstoreUserStateMockRecorder) SetRequestTags(ctx, chatID, tags any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRequestTags", reflect.TypeOf((*MockstoreUserState)(nil).SetRequestTags), ctx, chatID, tags)
}

// SetRequestURL mocks base method.
func (m *MockstoreUserState) SetRequestURL(ctx context.Context, chatID int64, link string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRequestURL", ctx, chatID, link)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetRequestURL indicates an expected call of SetRequestURL.
func (mr *MockstoreUserStateMockRecorder) SetRequestURL(ctx, chatID, link any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRequestURL", reflect.TypeOf((*MockstoreUserState)(nil).SetRequestURL), ctx, chatID, link)
}

// SetUserState mocks base method.
func (m *MockstoreUserState) SetUserState(ctx context.Context, chatID int64, newState int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetUserState", ctx, chatID, newState)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetUserState indicates an expected call of SetUserState.
func (mr *MockstoreUserStateMockRecorder) SetUserState(ctx, chatID, newState any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUserState", reflect.TypeOf((*MockstoreUserState)(nil).SetUserState), ctx, chatID, newState)
}

// MockscrapperClient is a mock of scrapperClient interface.
type MockscrapperClient struct {
	ctrl     *gomock.Controller
	recorder *MockscrapperClientMockRecorder
	isgomock struct{}
}

// MockscrapperClientMockRecorder is the mock recorder for MockscrapperClient.
type MockscrapperClientMockRecorder struct {
	mock *MockscrapperClient
}

// NewMockscrapperClient creates a new mock instance.
func NewMockscrapperClient(ctrl *gomock.Controller) *MockscrapperClient {
	mock := &MockscrapperClient{ctrl: ctrl}
	mock.recorder = &MockscrapperClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockscrapperClient) EXPECT() *MockscrapperClientMockRecorder {
	return m.recorder
}

// AddLink mocks base method.
func (m *MockscrapperClient) AddLink(ctx context.Context, chatID int64, link scrapperapi.AddLinkRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddLink", ctx, chatID, link)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddLink indicates an expected call of AddLink.
func (mr *MockscrapperClientMockRecorder) AddLink(ctx, chatID, link any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddLink", reflect.TypeOf((*MockscrapperClient)(nil).AddLink), ctx, chatID, link)
}

// DeleteChat mocks base method.
func (m *MockscrapperClient) DeleteChat(ctx context.Context, chatID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteChat", ctx, chatID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteChat indicates an expected call of DeleteChat.
func (mr *MockscrapperClientMockRecorder) DeleteChat(ctx, chatID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteChat", reflect.TypeOf((*MockscrapperClient)(nil).DeleteChat), ctx, chatID)
}

// DeleteLink mocks base method.
func (m *MockscrapperClient) DeleteLink(ctx context.Context, chatID int64, link scrapperapi.DeleteLinkRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLink", ctx, chatID, link)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteLink indicates an expected call of DeleteLink.
func (mr *MockscrapperClientMockRecorder) DeleteLink(ctx, chatID, link any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLink", reflect.TypeOf((*MockscrapperClient)(nil).DeleteLink), ctx, chatID, link)
}

// GetLinks mocks base method.
func (m *MockscrapperClient) GetLinks(ctx context.Context, chatID int64) (scrapperapi.ListLinksResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLinks", ctx, chatID)
	ret0, _ := ret[0].(scrapperapi.ListLinksResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLinks indicates an expected call of GetLinks.
func (mr *MockscrapperClientMockRecorder) GetLinks(ctx, chatID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLinks", reflect.TypeOf((*MockscrapperClient)(nil).GetLinks), ctx, chatID)
}

// RegisterChat mocks base method.
func (m *MockscrapperClient) RegisterChat(ctx context.Context, chatID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterChat", ctx, chatID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterChat indicates an expected call of RegisterChat.
func (mr *MockscrapperClientMockRecorder) RegisterChat(ctx, chatID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterChat", reflect.TypeOf((*MockscrapperClient)(nil).RegisterChat), ctx, chatID)
}
